openapi: 3.0.2
info:
  title: doctors API TARpe22
  version: 1.0.0
  description: >-
    # doctors API Tarpe22 Hajusrakenduste näidisrakendus 
    
    
    ### Error handling
    
    Errors are presented using the HTTP status codes 400-599. The response include a more detailed
    explanation about the error in the body.
    
    
    ```
    
    {
      "error": "Cleartext explanation of the error that occurred"
    }
    
    ```
    
    
    ### Generic API errors
    
    These error responses can be returned by any of the described endpoints.
    
    
    | HTTP status  |  Description |
    
    |---|---|
    
    | 400| Bad input parameters or invalid request. More information can be found in the response body.
    
    | 401| The consumer does not have access to the requested resource or the provided token is not valid.
    
    | 404| The requested resource can not be found or the user does not have access to the resource.
    
    | 5XX| A server error has occurred while processing the request.
paths:
  /doctors:
    summary: doctors object
    get:
      tags:
        - Doctors
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/doctorListItem'
              examples:
                List of doctors:
                  value:
                    -
                      id: 47
                      name: some text
                    -
                      id: 40
                      name: some text
          description: Success
      summary: Get all doctor names
  '/doctors/{id}':
    summary: Deal with doctor object
    get:
      tags:
        - Doctors
      parameters:
        -
          examples:
            First:
              value: '1'
          name: id
          description: Id of the doctor being requested
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/doctor'
              examples:
                One doctor:
                  value:
                    id: 36
                    name: some text
                    rating: 81
                doctor without rating:
                  value:
                    id: 61
                    name: some text
          description: Success
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                InvalidID:
                  value:
                    error: 'ID must be a whole number: ab12'
          description: |
            Invalid request path parameter
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                NotFound:
                  value:
                    error: doctor Not Found!
          description: doctor with given id does not exist
      summary: Get the doctor with given id
components:
  schemas:
    doctor:
      title: Root Type for doctor
      description: ''
      type: object
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
        rating:
          format: double
          type: number
      example:
        id: 1
        name: Jane Doe
        rating: 5
    doctorListItem:
      title: Root Type for doctorListItem
      description: ''
      type: object
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
      example:
        id: 1
        name: Joe Doe
    Error:
      title: Root Type for Error
      description: ''
      type: object
      properties:
        error:
          type: string
      example:
        error: Error message
